Vagrant.configure("2") do |config|
    # CentOS 7, 20 GB HDD, nothing extra
    config.vm.box = "centos/7"
    config.vm.box_version = "1905.1"

    # VM IP Address in the Private Network
    config.vm.network :private_network, ip: "192.168.100.10"
    config.vm.network "forwarded_port", guest:8080, host: 9092

    # Host's hostname
    config.vm.hostname = "jenkins-groovy"

    config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |vb|
    # Virtualbox VM name
        vb.name = "jenkins-groovy"
    end
    
    # Docker Installation Steps
    config.vm.provision "shell", inline: <<-SHELL
        # jq, net-tools required for troubleshooting needs
        yum install -y yum-utils
        # actual Docker Installation
        yum-config-manager \
            --add-repo \
            https://download.docker.com/linux/centos/docker-ce.repo
        yum install -y docker-ce docker-ce-cli containerd.io
        systemctl enable docker
        systemctl start docker
        # The docker daemon binds to a Unix socket /var/run/docker.sock which is owned by root:docker
        # Non-root user just needs to be added to the docker group.
        usermod -aG docker vagrant
        # Pull Jenkins image
        docker pull jenkins/jenkins:latest
        # Run Jenkins in Docker container
        docker run -d -p 8080:8080 -v /home/vagrant:/var/jenkins_home jenkins/jenkins:latest
        # Install specific tolls for linux
        yum install -y vim
    SHELL
end
